{% set name = "ogre-next" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/OGRECave/ogre-next/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7818085243018178730bdbe85a84d358e49b3b19e3ff65e02d33b008e778210d
    patches:
      - 0001-Add-option-to-force-pkg-config-on-Windows.patch
      - 0002-Include-suffix-in-binary-install-paths-on-Windows.patch
      - disable_cmake_modules_install.patch
      - 351.patch

build:
  number: 0
  run_exports:
    # See https://salsa.debian.org/ogre-team/ogre-next/-/blob/a27f70cd8c6b82e3fc207fefe557b43bc49634b4/debian/README.Debian
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    - make  # [not win]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxt  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libx11  # [linux]
    - libgl-devel  # [linux]
    - libegl-devel  # [linux]
    - freeimage
    - freetype
    - rapidjson
    - zlib
    - zziplib
  run:
    # workaround for https://github.com/conda-forge/xorg-libx11-feedstock/issues/15
    - xorg-libxfixes  # [linux]
    - xorg-libxt  # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxrandr  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libx11  # [linux]

# The path are compatible with the ogre-next Ubuntu package:
# See https://packages.ubuntu.com/source/jammy/amd64/ogre-next
test:
  commands:
    - test -f $PREFIX/include/OGRE-Next/OgreRoot.h  # [unix]
    - test -f $PREFIX/lib/pkgconfig/OGRE-Next.pc  # [unix]
    - test -f $PREFIX/lib/libOgreNextMain${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/OGRE-Next//RenderSystem_NULL${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\\OGRE-Next\\OgreRoot.h exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\OGRE-Next.pc exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\OgreNextMain.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\OGRE-Next\\RenderSystem_NULL.dll exit 1  # [win]

about:
  home: https://github.com/OGRECave/ogre-next
  license: MIT
  license_file: COPYING
  summary: aka ogre v2 - scene-oriented, flexible 3D C++ engine

extra:
  recipe-maintainers:
    - traversaro
    - wolfv
